# Generated by Django 3.1.5 on 2022-06-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vj9_app', '0003_auto_20220615_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uloge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('profesor', 'profesor'), ('student', 'student')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vj9_app.uloge'),
        ),
    ]
