# Generated by Django 3.1.5 on 2022-06-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vj9_app', '0004_auto_20220616_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.ForeignKey(choices=[('admin', 'admin'), ('profesor', 'profesor'), ('student', 'student')], null=True, on_delete=django.db.models.deletion.CASCADE, to='vj9_app.uloge'),
        ),
    ]
