# Generated by Django 3.1.5 on 2022-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj9_app', '0006_auto_20220616_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloge',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
